// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7VH8zCxs86F5AYrdarUeJEU0hCgFSkVk',
    appId: '1:5648053054:web:dd6795ddd81ec71f26f26f',
    messagingSenderId: '5648053054',
    projectId: 'digmap-ba28f',
    authDomain: 'digmap-ba28f.firebaseapp.com',
    storageBucket: 'digmap-ba28f.appspot.com',
    measurementId: 'G-0SKCNNLQPG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD11tbtK7WjpcjEzvmU5xgNCrL3wB3ZaGE',
    appId: '1:5648053054:android:42745e43e57d688526f26f',
    messagingSenderId: '5648053054',
    projectId: 'digmap-ba28f',
    storageBucket: 'digmap-ba28f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7PbBIlPFzdC-jfQYEH2UNUMvFMs-cD60',
    appId: '1:5648053054:ios:b40c71307422740526f26f',
    messagingSenderId: '5648053054',
    projectId: 'digmap-ba28f',
    storageBucket: 'digmap-ba28f.appspot.com',
    iosBundleId: 'com.example.digmap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7PbBIlPFzdC-jfQYEH2UNUMvFMs-cD60',
    appId: '1:5648053054:ios:b40c71307422740526f26f',
    messagingSenderId: '5648053054',
    projectId: 'digmap-ba28f',
    storageBucket: 'digmap-ba28f.appspot.com',
    iosBundleId: 'com.example.digmap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7VH8zCxs86F5AYrdarUeJEU0hCgFSkVk',
    appId: '1:5648053054:web:0a60dd6454a763a826f26f',
    messagingSenderId: '5648053054',
    projectId: 'digmap-ba28f',
    authDomain: 'digmap-ba28f.firebaseapp.com',
    storageBucket: 'digmap-ba28f.appspot.com',
    measurementId: 'G-TH8VYSHW6M',
  );
}
