// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAN74Tr-noHlHp2nyzWIcJOWstyWKNcZo',
    appId: '1:512251626680:web:0346fb1162e79d5366604d',
    messagingSenderId: '512251626680',
    projectId: 'gigmap-96097',
    authDomain: 'gigmap-96097.firebaseapp.com',
    storageBucket: 'gigmap-96097.appspot.com',
    measurementId: 'G-MRXHP08F4J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByFkdFEAe9gswJUzQcAhuGNsGOu4GSKi0',
    appId: '1:512251626680:android:bfc88fd6bfa083cf66604d',
    messagingSenderId: '512251626680',
    projectId: 'gigmap-96097',
    storageBucket: 'gigmap-96097.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUEoZUScpyK9Iq-8rEbs0HUDtNDRdjF0A',
    appId: '1:512251626680:ios:d01f7343db225f4f66604d',
    messagingSenderId: '512251626680',
    projectId: 'gigmap-96097',
    storageBucket: 'gigmap-96097.appspot.com',
    iosBundleId: 'com.example.digmap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUEoZUScpyK9Iq-8rEbs0HUDtNDRdjF0A',
    appId: '1:512251626680:ios:d01f7343db225f4f66604d',
    messagingSenderId: '512251626680',
    projectId: 'gigmap-96097',
    storageBucket: 'gigmap-96097.appspot.com',
    iosBundleId: 'com.example.digmap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAN74Tr-noHlHp2nyzWIcJOWstyWKNcZo',
    appId: '1:512251626680:web:0b110f76d60539af66604d',
    messagingSenderId: '512251626680',
    projectId: 'gigmap-96097',
    authDomain: 'gigmap-96097.firebaseapp.com',
    storageBucket: 'gigmap-96097.appspot.com',
    measurementId: 'G-VCQKLK2BFW',
  );
}
